# Rime schema
# encoding: utf-8


# æ–¹æ¡ˆè¯´æ˜
schema:
  schema_id: ahaooahaz_pinyin_simp
  name: é˜¿æ˜Šæ‹¼éŸ³
  version: "2024-02-25"
  author:
    - ahaooahaz
  description: |
    é˜¿æ˜Šæ‹¼éŸ³
    https://github.com/ahaooahaz/Annal/configs/rime
  dependencies:
    - radical_pinyin  # éƒ¨ä»¶æ‹†å­—ï¼ŒåæŸ¥åŠè¾…ç 

# å¼€å…³
# reset: é»˜è®¤çŠ¶æ€ã€‚æ³¨é‡Šæ‰åï¼Œåˆ‡æ¢çª—å£æ—¶ä¸ä¼šé‡ç½®åˆ°é»˜è®¤çŠ¶æ€ã€‚
# states: æ–¹æ¡ˆé€‰å•æ˜¾ç¤ºçš„åç§°ã€‚å¯ä»¥æ³¨é‡Šæ‰ï¼Œä»å¯ä»¥é€šè¿‡å¿«æ·é”®åˆ‡æ¢ã€‚
# abbrev: é»˜è®¤çš„ç¼©å†™å– states çš„ç¬¬ä¸€ä¸ªå­—ç¬¦ï¼Œabbrev å¯è‡ªå®šä¹‰ä¸€ä¸ªå­—ç¬¦
switches:
  - name: ascii_mode
    reset: 0
    states: [ ä¸­, A ]
  - name: ascii_punct  # ä¸­è‹±æ ‡ç‚¹
    states: [ Â¥, $ ]
  - name: full_shape
    states: ["åŠè§’", "å…¨è§’"]
  - name: traditionalization
    # reset: 1
    states: [ ç®€, ç¹ ]
  - name: emoji
    reset: 1
    states: ["ğŸˆšï¸", "ğŸˆ¶ï¸"]

engine:
  filters:
    - lua_filter@corrector                          # é”™éŸ³é”™å­—æç¤º
    - reverse_lookup_filter@radical_reverse_lookup  # éƒ¨ä»¶æ‹†å­—æ»¤é•œ
    - simplifier@emoji
    - simplifier@traditionalize                     # ç®€ç¹åˆ‡æ¢
    - uniquifier                                    # å»é‡
  processors:
    - lua_processor@select_character          # ä»¥è¯å®šå­—
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - affix_segmentor@radical_lookup  # éƒ¨ä»¶æ‹†å­—è‡ªå®šä¹‰ tag
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - script_translator
    - lua_translator@date_translator    # æ—¶é—´ã€æ—¥æœŸã€æ˜ŸæœŸ
    - lua_translator@lunar              # å†œå†
    - lua_translator@unicode            # Unicode
    - lua_translator@number_translator  # æ•°å­—ã€é‡‘é¢å¤§å†™
    - lua_translator@force_gc           # æš´åŠ› GC
    - table_translator@custom_phrase
    - table_translator@radical_lookup   # éƒ¨ä»¶æ‹†å­—åæŸ¥


# Lua é…ç½®: æ—¥æœŸã€æ—¶é—´ã€æ˜ŸæœŸã€ISO 8601ã€æ—¶é—´æˆ³çš„è§¦å‘å…³é”®å­—
date_translator:
  date: date       # æ—¥æœŸï¼š 2022-11-29
  time: time       # æ—¶é—´ï¼š 18:13
  week: week       # æ˜ŸæœŸï¼š æ˜ŸæœŸäºŒ
  datetime: datetime   # ISO 8601ï¼š 2022-11-29T18:13:11+08:00
  timestamp: timestamp  # æ—¶é—´æˆ³ï¼š 1669716794

# Lua é…ç½®ï¼šå†œå†çš„è§¦å‘å…³é”®å­—
lunar: nl  # å†œå†ï¼š äºŒã€‡äºŒä¸‰å¹´å†¬æœˆäºŒå ç™¸å¯å¹´ï¼ˆå…”ï¼‰å†¬æœˆäºŒå

# Lua é…ç½®ï¼šä¸º corrector æ ¼å¼åŒ– commentï¼Œå ä½ç¬¦ä¸º {comment}
# é»˜è®¤ "{comment}" è¾“å…¥ hun dun æ—¶ä¼šåœ¨ã€Œé¦„é¥¨ã€æ—è¾¹ç”Ÿæˆ hÃºn tun çš„ comment
# ä¾‹å¦‚å·¦å³åŠ ä¸ªæ‹¬å· "({comment})" å°±ä¼šå˜æˆ (hÃºn tun)
corrector: "{comment}"

translator:
  dictionary: rime_ice # æŒ‚è½½è¯åº“ rime_ice.dict.yaml
  spelling_hints: 8           # corrector.lua ï¼šä¸ºäº†è®©é”™éŸ³é”™å­—æç¤ºçš„ Lua åŒæ—¶é€‚é…å…¨æ‹¼åŒæ‹¼ï¼Œå°†æ‹¼éŸ³æ˜¾ç¤ºåœ¨ comment ä¸­
  always_show_comments: true  # corrector.lua ï¼šRime é»˜è®¤åœ¨ preedit ç­‰äº comment æ—¶å–æ¶ˆæ˜¾ç¤º commentï¼Œè¿™é‡Œå¼ºåˆ¶ä¸€ç›´æ˜¾ç¤ºï¼Œä¾› corrector.lua åšåˆ¤æ–­ç”¨ã€‚
  initial_quality: 1.2        # æ‹¼éŸ³çš„æƒé‡åº”è¯¥æ¯”è‹±æ–‡å¤§
  comment_format:             # æ ‡è®°æ‹¼éŸ³æ³¨é‡Šï¼Œä¾› corrector.lua åšåˆ¤æ–­ç”¨
    - xform/^/ï¼»/
    - xform/$/ï¼½/
  preedit_format:             # preedit_format å½±å“åˆ°è¾“å…¥æ¡†çš„æ˜¾ç¤ºå’Œâ€œShift+å›è½¦â€ä¸Šå±çš„å­—ç¬¦
    - xform/([jqxy])v/$1u/    # æ˜¾ç¤ºä¸º ju qu xu yu
    # - xform/([nl])v/$1Ã¼/    # æ˜¾ç¤ºä¸º nÃ¼ lÃ¼
    # - xform/([nl])ue/$1Ã¼e/  # æ˜¾ç¤ºä¸º nÃ¼e lÃ¼e
    - xform/([nl])v/$1v/      # æ˜¾ç¤ºä¸º nv lv
    - xform/([nl])ue/$1ve/    # æ˜¾ç¤ºä¸º nve lve

# è‡ªå®šä¹‰çŸ­è¯­ï¼šcustom_phrase.txt
custom_phrase:
  dictionary: ""
  user_dict: custom_phrase  # å¯ä»¥ä¿®æ”¹è¿™é‡Œï¼Œæ”¹æˆè‡ªå·±çš„ txt æ–‡ä»¶
  db_class: stabledb        # åªè¯»æ•°æ®åº“ï¼Œæ— æ³•åŠ¨æ€è°ƒé¢‘ï¼›è®¾ä¸º tabledb å¯ä»¥åŠ¨æ€è°ƒé¢‘
  enable_completion: false  # è¡¥å…¨æç¤º
  enable_sentence: false    # ç¦æ­¢é€ å¥
  initial_quality: 99       # custom_phrase çš„æƒé‡åº”è¯¥æ¯” pinyin å’Œ melt_eng å¤§


# Emoji
emoji:
  option_name: emoji
  opencc_config: emoji.json
  inherit_comment: false  # åœ¨ corrector.lua åŠåæŸ¥ä¸­ï¼Œemoji è¿”å›ç©ºæ³¨é‡Š

# ç®€ç¹åˆ‡æ¢
traditionalize:
  option_name: traditionalization
  opencc_config: s2t.json  # s2t.json | s2hk.json | s2tw.json | s2twp.json
  tips: none               # è½¬æ¢æç¤º: all éƒ½æ˜¾ç¤º | char ä»…å•å­—æ˜¾ç¤º | none ä¸æ˜¾ç¤ºã€‚
  tags: [ abc, number, gregorian_to_lunar ]  # é™åˆ¶åœ¨å¯¹åº” tagï¼Œä¸å¯¹å…¶ä»–å¦‚åæŸ¥çš„å†…å®¹åšç®€ç¹è½¬æ¢


# æ ‡ç‚¹ç¬¦å·
# punctuator ä¸‹é¢æœ‰ä¸‰ä¸ªå­é¡¹ï¼š
#   full_shape å…¨è§’æ ‡ç‚¹æ˜ å°„
#   half_shape åŠè§’æ ‡ç‚¹æ˜ å°„
#   symbols    Rime çš„é¢„è®¾é…ç½®æ˜¯ä»¥ '/' å‰ç¼€å¼€å¤´è¾“å‡ºä¸€ç³»åˆ—å­—ç¬¦ï¼Œè‡ªå®šä¹‰çš„ symbols_v.yaml ä¿®æ”¹æˆäº† 'v' å¼€å¤´ã€‚
punctuator:
  full_shape:
    __include: default:/punctuator/full_shape  # ä» default.yaml å¯¼å…¥é…ç½®
  half_shape:
    __include: default:/punctuator/half_shape  # ä» default.yaml å¯¼å…¥é…ç½®
  symbols:
    __include: symbols_v:/symbols              # ä» symbols_v.yaml å¯¼å…¥é…ç½®

key_binder:
  import_preset: default
  search: "`"             # è¾…ç å¼•å¯¼ç¬¦ï¼Œè¦æ·»åŠ åˆ° speller/alphabet


# å¤„ç†ç¬¦åˆç‰¹å®šè§„åˆ™çš„è¾“å…¥ç ï¼Œå¦‚ç½‘å€ã€åæŸ¥
recognizer:
  import_preset: default  # ä» default.yaml ç»§æ‰¿é€šç”¨çš„
  patterns:  # å†å¢åŠ æ–¹æ¡ˆä¸“æœ‰çš„ï¼š
    punct: "^v([0-9]|10|[A-Za-z]+)$"    # å“åº” symbols_v.yaml çš„ symbolsï¼Œç”¨ 'v' æ›¿æ¢ '/'
    radical_lookup: "^uU[a-z]+$"        # å“åº”éƒ¨ä»¶æ‹†å­—çš„åæŸ¥ï¼Œä¸ radical_lookup/prefix åŒ¹é…
    unicode: "^U[a-f0-9]+"              # è„šæœ¬å°†è‡ªåŠ¨è·å–ç¬¬ 2 ä¸ªå­—ç¬¦ U ä½œä¸ºè§¦å‘å‰ç¼€ï¼Œå“åº” lua_translator@unicodeï¼Œè¾“å‡º Unicode å­—ç¬¦
    number: "^R[0-9]+[.]?[0-9]*"        # è„šæœ¬å°†è‡ªåŠ¨è·å–ç¬¬ 2 ä¸ªå­—ç¬¦ R ä½œä¸ºè§¦å‘å‰ç¼€ï¼Œå“åº” lua_translator@number_translatorï¼Œæ•°å­—é‡‘é¢å¤§å†™
    gregorian_to_lunar: "^N[0-9]{1,8}"  # è„šæœ¬å°†è‡ªåŠ¨è·å–ç¬¬ 2 ä¸ªå­—ç¬¦ N ä½œä¸ºè§¦å‘å‰ç¼€ï¼Œå“åº” lua_translator@lunarï¼Œå…¬å†è½¬å†œå†ï¼Œè¾“å…¥ N20240115 å¾—åˆ°ã€ŒäºŒã€‡äºŒä¸‰å¹´è…Šæœˆåˆäº”ã€



# éƒ¨ä»¶æ‹†å­—åæŸ¥
radical_lookup:
  tag: radical_lookup
  dictionary: radical_pinyin
  enable_user_dict: false
  prefix: "uU"  # åæŸ¥å‰ç¼€ï¼ˆåæŸ¥æ—¶å‰ç¼€ä¼šæ¶ˆå¤±å½±å“æ‰“è‹±æ–‡æ‰€ä»¥è®¾å®šä¸ºä¸¤ä¸ªå­—æ¯ï¼Œæˆ–å¯æ”¹æˆä¸€ä¸ªéå­—æ¯ç¬¦å·ï¼‰ï¼Œä¸ recognizer/patterns/radical_lookup åŒ¹é…
  tips: "  ã€”æ‹†å­—ã€•"
  comment_format:
    - erase/^.*$//
# éƒ¨ä»¶æ‹†å­—æ»¤é•œ
radical_reverse_lookup:
  tags: [ radical_lookup ]
  # dictionary ä¸ºæ‹¼éŸ³æ ‡æ³¨æ¥æºã€‚ç›®å‰æ˜¯æ˜¾ç¤ºæœ¬æ–¹æ¡ˆè¯åº“çš„æ³¨éŸ³ï¼Œå¯å»éƒ¨ä»¶æ‹†å­—æ–¹æ¡ˆä¸‹è½½æ›´å…¨çš„ã€å¸¦å£°è°ƒçš„ã€å·²ç¼–è¯‘å¥½çš„è¯å…¸
  # https://github.com/mirtlecn/rime-radical-pinyin?tab=readme-ov-file#%E5%8F%8D%E6%9F%A5%E5%B8%A6%E5%A3%B0%E8%B0%83%E6%B3%A8%E9%9F%B3
  dictionary: rime_ice
  # comment_format:     # è‡ªå®šä¹‰ commentï¼Œä¾‹å¦‚åœ¨å·¦å³åŠ ä¸Šæ‹¬å·
  #  - xform/^/(/
  #  - xform/$/)/


speller:
  # å¦‚æœä¸æƒ³è®©ä»€ä¹ˆæ ‡ç‚¹ç›´æ¥ä¸Šå±ï¼Œå¯ä»¥åŠ åœ¨ alphabetï¼Œæˆ–è€…ç¼–è¾‘æ ‡ç‚¹ç¬¦å·ä¸ºä¸¤ä¸ªåŠä»¥ä¸Šçš„æ˜ å°„
  alphabet: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA`
  # initials å®šä¹‰ä»…ä½œä¸ºå§‹ç çš„æŒ‰é”®ï¼Œæ’é™¤ ` è®©å•ä¸ªçš„ ` å¯ä»¥ç›´æ¥ä¸Šå±
  initials: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA
  delimiter: " '"  # ç¬¬ä¸€ä½<ç©ºæ ¼>æ˜¯æ‹¼éŸ³ä¹‹é—´çš„åˆ†éš”ç¬¦ï¼›ç¬¬äºŒä½<'>è¡¨ç¤ºå¯ä»¥æ‰‹åŠ¨è¾“å…¥å•å¼•å·æ¥åˆ†å‰²æ‹¼éŸ³ã€‚
  algebra:
    - "erase/^xx$/"
    - "abbrev/^([a-z]).+$/$1/"
    - "abbrev/^([zcs]h).+$/$1/"
    - "derive/^([nl])ve$/$1ue/"
    - "derive/^([jqxy])u/$1v/"
    - "derive/un$/uen/"
    - "derive/ui$/uei/"
    - "derive/iu$/iou/"
    - "derive/([aeiou])ng$/$1gn/"
    - "derive/([dtngkhrzcs])o(u|ng)$/$1o/"
    - "derive/ong$/on/"
    - "derive/ao$/oa/"
    - "derive/([iu])a(o|ng?)$/a$1$2/"
